# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3465b13f612aef720cb08fa17f7f7c0524732bec1ea5bc3e23112a0d6c08945a713d012a37d48df2cc3706f938b2b69a9eb4ed2b581c7a8ac9f5ddfbf5c7413

test:
  secret_key_base: 447f47cffd1386f8fbc3fe8b59175e385c15988c1f6418c7989fcdc1d9ae77d2b0a1a6c340a8fbf19b861090e600c355373041205a38319cf54bbe244adde7e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
